### PR TITLE
Closes #341 Gitlab Integration

### LINKED ISSUE #341: [new feature] GitLab integration
[Gitlab](https://gitlab.com/) is a service analogous to Github. We don't have to always support Microsoft that owns github, do we?

Let's make a Gitlab integration and make Refact work with issues, merge requests, maybe CI, etc. For functionality you can look at what [Github integration](https://github.com/smallcloudai/refact-lsp/blob/main/src/integrations/integr_github.rs) provides: creating issues, commenting, searching.

It's not clear at this point if they have a command line utility or REST API in Gitlab. Both can be integrated quite easily, a change to only 2 files required (1 file for the new integration, and `tools_description.rs`)

[CONTRIBUTING](https://github.com/smallcloudai/refact-lsp/blob/main/CONTRIBUTING.md)

### PR DESCRIPTION
**Pull request by Commit2Cosmos**
Implemented a GitLab integration tool following the github tool implementation. Tested by creating a repo in gitlab and prompting the agent to create a new issue and comments in it.

### CODE REVIEW

**Comment by olegklimov** [comment]
Oh cool, nice and easy!

**Comment by olegklimov** [comment]
Now how do I test it ... 🤔

**Comment by olegklimov** [comment]
image

Believe it or not, the integration worked on the first try!

Here, I created an issue in the chat above:

https://gitlab.com/refact_integration/hello_world/-/issues/1

**Review by olegklimov — APPROVED** [review]

**Comment by olegklimov** [comment]
merged, nice job 🙇

**Comment by Commit2Cosmos** [comment]
That's amazing! Thank you for you guidance and support!

**Pull request merged**
